FROM node:16-alpine

WORKDIR /app

RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN apk add --update python3 krb5 krb5-libs gcc make g++ krb5-dev

RUN npm install -g ganache-cli

# RUN export NODE_OPTIONS=--openssl-legacy-provider

CMD ["ganache-cli","-h","0.0.0.0", "--networkId", "2020"]
